name: maxbillup
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  http: ^1.2.0
  mobile_scanner: ^5.2.3
  fl_chart: ^0.70.1
  intl: ^0.19.0
  google_sign_in: ^6.2.2
  pdf: ^3.11.1
  printing: 5.13.4
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  permission_handler: ^12.0.1
  flutter_blue_plus: ^1.32.12
  charset_converter: ^2.1.2
  flutter_contacts: ^1.1.9
  share_plus: ^10.1.2
  provider: ^6.1.2
  razorpay_flutter: ^1.3.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  google_places_flutter: ^2.1.1
  file_picker: ^8.1.6
  excel: ^4.0.6
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  image_cropper: ^11.0.0
  in_app_update: ^4.2.5
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/MAX_my_bill_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#4A5DF9"
  image: assets/Splash_Screen.png
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  web: false
  android_12:
    color: "#4A5DF9"
    image: assets/Splash_Screen.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # SF Pro Display fonts
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans-Medium.ttf
          weight: 300
        - asset: fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700

  # Application assets
  assets:
    - assets/google.png
    - assets/MAX_my_bill_icon.png
    - assets/MAX_my_bill_mobile.png
    - assets/MAX_my_bill_tab.png
    - assets/MAX_my_bill_mobile.png
    - assets/MAX_my_bill_mic.png
    - assets/Upgrade_Now.png
    - assets/Update_Now.png
    - assets/Start_Billing.png
    - assets/View_Report.png
    - assets/Splash_Screen.png
